In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/crime-cast-forecasting-crime-categories/sample.csv
/kaggle/input/crime-cast-forecasting-crime-categories/train.csv
/kaggle/input/crime-cast-forecasting-crime-categories/test.csv


In [2]:
train=pd.read_csv('/kaggle/input/crime-cast-forecasting-crime-categories/train.csv')

In [3]:
train


Location  \
0       4500    CARPENTER                    AV   
1               45TH                         ST   
2        600 E  MARTIN LUTHER KING JR        BL   
3      14900    ORO GRANDE                   ST   
4       7100 S  VERMONT                      AV   
...                                         ...   
19995   5100 W  ADAMS                        BL   
19996  16900    ROSCOE                       BL   
19997   1000 S  SHENANDOAH                   ST   
19998    300 W  SEPULVEDA                    ST   
19999           DALTON                       AV   

                          Cross_Street  Latitude  Longitude  \
0                                  NaN   34.1522  -118.3910   
1      ALAMEDA                      ST   34.0028  -118.2391   
2                                  NaN   34.0111  -118.2653   
3                                  NaN   34.2953  -118.4590   
4                                  NaN   33.9787  -118.2918   
...                                ...       ...        ...   
19995                              NaN   34.0334  -118.3523   
19996                              NaN   34.2212  -118.5011   
19997                              NaN   34.0571  -118.3815   
19998                              NaN   33.7451  -118.2835   
19999  VERNON                       AV   34.0037  -118.3034   

                Date_Reported           Date_Occurred  Time_Occurred  Area_ID  \
0      03/09/2020 12:00:00 AM  03/06/2020 12:00:00 AM         1800.0     15.0   
1      02/27/2020 12:00:00 AM  02/27/2020 12:00:00 AM         1345.0     13.0   
2      08/21/2020 12:00:00 AM  08/21/2020 12:00:00 AM          605.0     13.0   
3      11/08/2020 12:00:00 AM  11/06/2020 12:00:00 AM         1800.0     19.0   
4      02/25/2020 12:00:00 AM  02/25/2020 12:00:00 AM         1130.0     12.0   
...                       ...                     ...            ...      ...   
19995  05/24/2020 12:00:00 AM  05/24/2020 12:00:00 AM          700.0      3.0   
19996  12/25/2020 12:00:00 AM  12/25/2020 12:00:00 AM          259.0     10.0   
19997  09/25/2020 12:00:00 AM  09/25/2020 12:00:00 AM         1400.0      8.0   
19998  06/10/2020 12:00:00 AM  06/10/2020 12:00:00 AM          600.0      5.0   
19999  02/18/2020 12:00:00 AM  02/17/2020 12:00:00 AM         1800.0      3.0   

         Area_Name  Reporting_District_no  ...  Victim_Age Victim_Sex  \
0      N Hollywood                 1563.0  ...        75.0          M   
1           Newton                 1367.0  ...        41.0          M   
2           Newton                 1343.0  ...        67.0          M   
3          Mission                 1924.0  ...        61.0          M   
4      77th Street                 1245.0  ...         0.0          X   
...            ...                    ...  ...         ...        ...   
19995    Southwest                  303.0  ...        51.0          M   
19996  West Valley                 1008.0  ...         0.0          M   
19997      West LA                  849.0  ...        42.0          M   
19998       Harbor                  558.0  ...        76.0          F   
19999    Southwest                  397.0  ...         0.0        NaN   

       Victim_Descent Premise_Code     Premise_Description  Weapon_Used_Code  \
0                   W        101.0                  STREET               NaN   
1                   H        216.0               SWAP MEET             400.0   
2                   B        501.0  SINGLE FAMILY DWELLING               NaN   
3                   H        101.0                  STREET               NaN   
4                   X        401.0               MINI-MART             400.0   
...               ...          ...                     ...               ...   
19995               H        501.0  SINGLE FAMILY DWELLING             400.0   
19996               W        301.0             GAS STATION               NaN   
19997               H        102.0                SIDEWALK               NaN   
19998              

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Location               20000 non-null  object 
 1   Cross_Street           3448 non-null   object 
 2   Latitude               20000 non-null  float64
 3   Longitude              20000 non-null  float64
 4   Date_Reported          20000 non-null  object 
 5   Date_Occurred          20000 non-null  object 
 6   Time_Occurred          20000 non-null  float64
 7   Area_ID                20000 non-null  float64
 8   Area_Name              20000 non-null  object 
 9   Reporting_District_no  20000 non-null  float64
 10  Part 1-2               20000 non-null  float64
 11  Modus_Operandi         17259 non-null  object 
 12  Victim_Age             20000 non-null  float64
 13  Victim_Sex             17376 non-null  object 
 14  Victim_Descent         17376 non-null  object 
 15  Pr

In [5]:
train['Part 1-2'].unique()

array([1., 2.])

In [6]:
train['Reporting_District_no'].unique()

array([1563., 1367., 1343., ..., 1778., 1199.,  812.])

In [7]:
train['Area_Name'].unique()

array(['N Hollywood', 'Newton', 'Mission', '77th Street', 'Northeast',
       'Hollenbeck', 'Pacific', 'Van Nuys', 'Devonshire', 'Wilshire',
       'Hollywood', 'Harbor', 'Topanga', 'Central', 'West Valley',
       'Olympic', 'Foothill', 'West LA', 'Southeast', 'Southwest',
       'Rampart'], dtype=object)

In [8]:
train['Area_ID'].value_counts()

Area_ID
12.0    1345
14.0    1157
1.0     1156
3.0     1130
18.0    1067
15.0    1065
6.0     1014
13.0     999
20.0     960
7.0      943
2.0      931
8.0      910
9.0      902
5.0      872
19.0     870
11.0     839
21.0     792
10.0     790
17.0     769
4.0      755
16.0     734
Name: count, dtype: int64

In [9]:
train['Premise_Code'].unique()

array([101., 216., 501., 401., 502., 202., 104., 108., 121., 102., 203.,
       122., 707., 503., 506., 509., 710., 103., 602., 519., 406., 751.,
       210., 123., 801., 601., 243., 242., 504., 124., 505., 119., 252.,
       109., 704., 152., 120., 301., 404., 720., 405., 402., 213., 514.,
       248., 702., 708., 834., 212., 416., 954., 158., 403., 701., 721.,
       725., 605., 726., 912., 729., 139., 145., 208., 719., 201., 141.,
       107., 222., 144., 116., 507., 221., 254., 757., 217., 110., 408.,
       146., 510., 750., 229., 727., 249., 236., 738., 516., 735., 716.,
       908., 232., 517., 722., 515., 874., 518., 118., 127., 151., 932.,
       411., 415., 910., 414., 220., 255., 407., 239., 156., 233., 717.,
       900., 956., 949., 218., 732., 936., 244., 835., 715., 410., 231.,
       728., 417., 207., 247., 206., 913., 733., 409., 811., 235., 724.,
       902., 712., 941., 117., 412., 705., 512., 907., 142., 903., 953.,
       511., 753., 736., 205., 897., 875., 138., 70

In [10]:
train['Victim_Descent'].unique()

array(['W', 'H', 'B', 'X', nan, 'O', 'A', 'K', 'C', 'F', 'I', 'J', 'Z',
       'V', 'P', 'D', 'U', 'G'], dtype=object)

In [11]:
train['Victim_Sex'].unique()

array(['M', 'X', 'F', nan, 'H'], dtype=object)

In [12]:
train['Victim_Age'].unique()

array([75., 41., 67., 61.,  0., 50., 68., 22., 31., 46., 72., 26., 38.,
       37., 42., 40., 53., 60., 29., 13., 33., 27., 15., 23., 74., 63.,
       78., 51., 44., 34., 69., 36., 52., 25., 49., 48., 32., 18., 35.,
       24., 39., 16., 28., 47., 30., 64., 76.,  5., 58., 45., 57., 19.,
       55., 54., 21., 65., 17., 20., 77., 82., 56., -2., 84., 59., 43.,
        7., 70., 66., 62., 14., 80., 71., 81., 96., 12., 11.,  4., 83.,
       10.,  8.,  6., 88., 86., 73.,  9., 87., 85., 93., 95., 99., 79.,
        3.,  2., 91., 92., 90., 89., 98., -1., 94.])

In [13]:
train['Modus_Operandi'].unique()

array(['0385', '0906 0352 0371 0446 1822 0344 0416 0417', '0329 1202',
       ..., '0416 0446 2004 0913', '1822 0209 0344 1414 1420',
       '1202 2038 0913 0602 1242 0553'], dtype=object)

In [14]:
train['Premise_Description'].unique()

array(['STREET', 'SWAP MEET', 'SINGLE FAMILY DWELLING', 'MINI-MART',
       'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)', 'LIQUOR STORE',
       'DRIVEWAY', 'PARKING LOT', 'YARD (RESIDENTIAL/BUSINESS)',
       'SIDEWALK', 'OTHER BUSINESS', 'VEHICLE, PASSENGER/TRUCK',
       'GARAGE/CARPORT', 'HOTEL', 'ABANDONED BUILDING ABANDONED HOUSE',
       "MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV'S/MOTORHOME",
       'OTHER PREMISE', 'ALLEY', 'BANK', 'SHORT-TERM VACATION RENTAL',
       'OTHER STORE', 'WEBSITE', 'RESTAURANT/FAST FOOD',
       'PARKING UNDERGROUND/BUILDING', 'MTA BUS', 'SAVINGS & LOAN',
       "DIY CENTER (LOWE'S,HOME DEPOT,OSH,CONTRACTORS WAREHOUSE)",
       'DISCOUNT STORE (99 CENT,DOLLAR,ETC.', 'OTHER RESIDENCE',
       'BUS STOP', 'MOTEL', 'PORCH, RESIDENTIAL',
       "COFFEE SHOP (STARBUCKS, COFFEE BEAN, PEET'S, ETC.)",
       'PARK/PLAYGROUND', 'ELEMENTARY SCHOOL', 'UNDERPASS/BRIDGE*',
       'STORAGE SHED', 'GAS STATION', 'DEPARTMENT STORE',
       'JUNIOR HIGH SCHOO

In [15]:
train['Weapon_Used_Code'].unique()

array([ nan, 400., 511., 207., 102., 500., 307., 506., 312., 200., 302.,
       304., 109., 306., 215., 106., 114., 112., 305., 223., 204., 311.,
       515., 512., 218., 309., 212., 205., 103., 201., 219., 308., 113.,
       301., 310., 211., 214., 101., 107., 216., 111., 221., 104., 303.,
       206., 514., 105., 503., 510., 504., 501., 202., 513., 508., 210.,
       122., 115., 213.])

In [16]:
train['Weapon_Description'].unique()

array([nan, 'STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)',
       'VERBAL THREAT', 'OTHER KNIFE', 'HAND GUN',
       'UNKNOWN WEAPON/OTHER WEAPON', 'VEHICLE', 'FIRE',
       'PIPE/METAL PIPE', 'KNIFE WITH BLADE 6INCHES OR LESS',
       'BLUNT INSTRUMENT', 'CLUB/BAT', 'SEMI-AUTOMATIC PISTOL',
       'ROCK/THROWN OBJECT', 'MACHETE', 'UNKNOWN FIREARM',
       'AIR PISTOL/REVOLVER/RIFLE/BB GUN', 'TOY GUN', 'FIXED OBJECT',
       'UNKNOWN TYPE CUTTING INSTRUMENT', 'FOLDING KNIFE', 'HAMMER',
       'PHYSICAL PRESENCE', 'MACE/PEPPER SPRAY',
       'OTHER CUTTING INSTRUMENT', 'BOARD', 'BOTTLE', 'KITCHEN KNIFE',
       'RIFLE', 'KNIFE WITH BLADE OVER 6 INCHES IN LENGTH', 'SCREWDRIVER',
       'STICK', 'SIMULATED GUN', 'BELT FLAILING INSTRUMENT/CHAIN',
       'CONCRETE BLOCK/BRICK', 'AXE', 'ICE PICK', 'REVOLVER',
       'OTHER FIREARM', 'SCISSORS', 'STARTER PISTOL/REVOLVER', 'GLASS',
       'SHOTGUN', 'BRASS KNUCKLES', 'SWITCH BLADE', 'TIRE IRON',
       'SAWED OFF RIFLE/SHOTGUN', 'CAUSTIC CH

In [17]:
train['Crime_Category'].unique()

array(['Property Crimes', 'Violent Crimes', 'Other Crimes',
       'Crimes against Public Order', 'Fraud and White-Collar Crimes',
       'Crimes against Persons'], dtype=object)

In [18]:
train['Status_Description'].unique()

array(['Invest Cont', 'Adult Other', 'Adult Arrest', 'Juv Arrest',
       'Juv Other'], dtype=object)

In [19]:
train['Status'].unique()

array(['IC', 'AO', 'AA', 'JA', 'JO'], dtype=object)

In [20]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Location               20000 non-null  object 
 1   Cross_Street           3448 non-null   object 
 2   Latitude               20000 non-null  float64
 3   Longitude              20000 non-null  float64
 4   Date_Reported          20000 non-null  object 
 5   Date_Occurred          20000 non-null  object 
 6   Time_Occurred          20000 non-null  float64
 7   Area_ID                20000 non-null  float64
 8   Area_Name              20000 non-null  object 
 9   Reporting_District_no  20000 non-null  float64
 10  Part 1-2               20000 non-null  float64
 11  Modus_Operandi         17259 non-null  object 
 12  Victim_Age             20000 non-null  float64
 13  Victim_Sex             17376 non-null  object 
 14  Victim_Descent         17376 non-null  object 
 15  Pr

In [21]:
train1=train[['Latitude','Longitude','Date_Reported','Date_Occurred','Time_Occurred','Area_ID','Victim_Age','Victim_Sex','Premise_Description','Weapon_Used_Code','Status','Crime_Category']]

In [22]:
train1

Latitude  Longitude           Date_Reported           Date_Occurred  \
0       34.1522  -118.3910  03/09/2020 12:00:00 AM  03/06/2020 12:00:00 AM   
1       34.0028  -118.2391  02/27/2020 12:00:00 AM  02/27/2020 12:00:00 AM   
2       34.0111  -118.2653  08/21/2020 12:00:00 AM  08/21/2020 12:00:00 AM   
3       34.2953  -118.4590  11/08/2020 12:00:00 AM  11/06/2020 12:00:00 AM   
4       33.9787  -118.2918  02/25/2020 12:00:00 AM  02/25/2020 12:00:00 AM   
...         ...        ...                     ...                     ...   
19995   34.0334  -118.3523  05/24/2020 12:00:00 AM  05/24/2020 12:00:00 AM   
19996   34.2212  -118.5011  12/25/2020 12:00:00 AM  12/25/2020 12:00:00 AM   
19997   34.0571  -118.3815  09/25/2020 12:00:00 AM  09/25/2020 12:00:00 AM   
19998   33.7451  -118.2835  06/10/2020 12:00:00 AM  06/10/2020 12:00:00 AM   
19999   34.0037  -118.3034  02/18/2020 12:00:00 AM  02/17/2020 12:00:00 AM   

       Time_Occurred  Area_ID  Victim_Age Victim_Sex     Premise_Description  \
0             1800.0     15.0        75.0          M                  STREET   
1             1345.0     13.0        41.0          M               SWAP MEET   
2              605.0     13.0        67.0          M  SINGLE FAMILY DWELLING   
3             1800.0     19.0        61.0          M                  STREET   
4             1130.0     12.0         0.0          X               MINI-MART   
...              ...      ...         ...        ...                     ...   
19995          700.0      3.0        51.0          M  SINGLE FAMILY DWELLING   
19996          259.0     10.0         0.0          M             GAS STATION   
19997         1400.0      8.0        42.0          M                SIDEWALK   
19998          600.0      5.0        76.0          F  SINGLE FAMILY DWELLING   
19999         1800.0      3.0         0.0        NaN                  STREET   

       Weapon_Used_Code Status               Crime_Category  
0                   NaN     IC              Property Crimes  
1                 400.0     IC              Property Crimes  
2                   NaN     IC              Property Crimes  
3                   NaN     IC              Property Crimes  
4                 400.0     IC              Property Crimes  
...                 ...    ...                          ...  
19995             400.0     IC               Violent Crimes  
19996               NaN     IC              Property Crimes  
19997               NaN     IC              Property Crimes  
19998               NaN     IC  Crimes against Public Order  
19999               NaN     IC              Property Crimes  

[20000 rows x 12 columns]

In [23]:
train1['Date_Occurred']

0        03/06/2020 12:00:00 AM
1        02/27/2020 12:00:00 AM
2        08/21/2020 12:00:00 AM
3        11/06/2020 12:00:00 AM
4        02/25/2020 12:00:00 AM
                  ...          
19995    05/24/2020 12:00:00 AM
19996    12/25/2020 12:00:00 AM
19997    09/25/2020 12:00:00 AM
19998    06/10/2020 12:00:00 AM
19999    02/17/2020 12:00:00 AM
Name: Date_Occurred, Length: 20000, dtype: object

In [24]:
label=train1['Crime_Category']
train1=train1.drop('Crime_Category',axis=1)

In [25]:
train1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Latitude             20000 non-null  float64
 1   Longitude            20000 non-null  float64
 2   Date_Reported        20000 non-null  object 
 3   Date_Occurred        20000 non-null  object 
 4   Time_Occurred        20000 non-null  float64
 5   Area_ID              20000 non-null  float64
 6   Victim_Age           20000 non-null  float64
 7   Victim_Sex           17376 non-null  object 
 8   Premise_Description  19995 non-null  object 
 9   Weapon_Used_Code     7335 non-null   float64
 10  Status               20000 non-null  object 
dtypes: float64(6), object(5)
memory usage: 1.7+ MB


In [26]:
label

0                    Property Crimes
1                    Property Crimes
2                    Property Crimes
3                    Property Crimes
4                    Property Crimes
                    ...             
19995                 Violent Crimes
19996                Property Crimes
19997                Property Crimes
19998    Crimes against Public Order
19999                Property Crimes
Name: Crime_Category, Length: 20000, dtype: object

In [27]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(train1,label,test_size=0.2,random_state=1,shuffle=True,stratify=label)

In [28]:
xtrain

Latitude  Longitude           Date_Reported           Date_Occurred  \
2777    34.0076  -118.2583  05/11/2020 12:00:00 AM  05/08/2020 12:00:00 AM   
13011   34.2647  -118.4019  06/22/2020 12:00:00 AM  06/21/2020 12:00:00 AM   
6112    33.9747  -118.2827  06/15/2020 12:00:00 AM  06/15/2020 12:00:00 AM   
10185   34.0757  -118.1711  01/17/2020 12:00:00 AM  01/14/2020 12:00:00 AM   
11906   33.9433  -118.2541  09/15/2020 12:00:00 AM  09/15/2020 12:00:00 AM   
...         ...        ...                     ...                     ...   
4672    33.9994  -118.2456  06/18/2020 12:00:00 AM  06/17/2020 12:00:00 AM   
17352   34.0734  -118.3765  07/14/2020 12:00:00 AM  07/14/2020 12:00:00 AM   
15682   34.0816  -118.3627  10/29/2020 12:00:00 AM  10/28/2020 12:00:00 AM   
4633    33.9542  -118.2684  04/03/2020 12:00:00 AM  04/03/2020 12:00:00 AM   
19598   33.9538  -118.4407  09/30/2020 12:00:00 AM  09/30/2020 12:00:00 AM   

       Time_Occurred  Area_ID  Victim_Age Victim_Sex  \
2777          1700.0     13.0        57.0          F   
13011         1800.0     16.0        49.0          M   
6112          1905.0     12.0         0.0          X   
10185         1800.0      4.0        51.0          M   
11906          905.0     18.0        30.0          M   
...              ...      ...         ...        ...   
4672          1400.0     13.0         0.0        NaN   
17352         1600.0      7.0        22.0          M   
15682         2100.0      7.0         0.0        NaN   
4633           230.0     18.0         0.0        NaN   
19598         1700.0     14.0        37.0          F   

                                Premise_Description  Weapon_Used_Code Status  
2777   MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)               NaN     IC  
13011                      VEHICLE, PASSENGER/TRUCK               NaN     IC  
6112                           RESTAURANT/FAST FOOD               NaN     IC  
10185                                PUBLIC STORAGE               NaN     IC  
11906                                   PARKING LOT             511.0     IC  
...                                             ...               ...    ...  
4672                                         STREET               NaN     IC  
17352                                   PARKING LOT             500.0     AO  
15682                                        STREET               NaN     IC  
4633                                         STREET               NaN     IC  
19598                        OFFICE BUILDING/OFFICE               NaN     IC  

[16000 rows x 11 columns]

In [29]:
xtrain.isnull().sum()

Latitude                   0
Longitude                  0
Date_Reported              0
Date_Occurred              0
Time_Occurred              0
Area_ID                    0
Victim_Age                 0
Victim_Sex              2084
Premise_Description        5
Weapon_Used_Code       10128
Status                     0
dtype: int64

In [30]:
xtrain['Victim_Sex'].unique()

array(['F', 'M', 'X', nan, 'H'], dtype=object)

In [31]:
xtrain['Victim_Sex'].value_counts()

Victim_Sex
M    6842
F    5736
X    1337
H       1
Name: count, dtype: int64